name: Build Project with Pygbag
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-pygbag:
    name: Build Project
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Checkout
      run: |
            echo "trying to install pygbag"
            python -m pip install pygbag
            echo "successfully installed pygbag"
            echo "trying to build the game"
            python -m pygbag --build $GITHUB_WORKSPACE/src/main.py
            echo "successfully built the game and compiled to WebAssembly"

    - name : "Upload to GitHub pages branch gh-pages"
      uses: JamesIves/github-pages-deploy-action@4.1.7
      with:
        branch: gh-pages
        folder: src/build/web
